# Generated by Django 3.1.2 on 2021-05-22 17:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0)),
                ('p_id', models.IntegerField(default=0)),
                ('f_id', models.IntegerField(default=0)),
                ('mesh_id', models.IntegerField(default=0)),
                ('ims_id', models.IntegerField(default=0)),
                ('def_id', models.IntegerField(default=0)),
                ('rand_id', models.CharField(max_length=74, validators=[django.core.validators.MinLengthValidator(44)])),
                ('project_name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPS',
            fields=[
                ('gps_id', models.AutoField(primary_key=True, serialize=False)),
                ('rand_id', models.CharField(max_length=74, validators=[django.core.validators.MinLengthValidator(44)])),
                ('gps_latitude', models.DecimalField(decimal_places=8, default=1.0, max_digits=12)),
                ('gps_longitude', models.DecimalField(decimal_places=8, default=1.0, max_digits=12)),
                ('gps_height', models.DecimalField(decimal_places=8, default=1.0, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wmq_api.project')),
            ],
        ),
    ]
